apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cert-example.fullname" . }}
  labels:
    {{- include "cert-example.labels" . | nindent 4 }}
spec:
  secretName: {{ include "cert-example.fullname" . }}

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  isCA: false
  usages:
    - server auth
    - client auth

  dnsNames:
{{- range .Values.dnsNames }}
  - {{ . }}
{{ end }}
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: {{ .Values.issuer.kind }}
