apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cert-example.fullname" . }}
  labels:
    {{- include "cert-example.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cert-example.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cert-example.labels" . | nindent 8 }}
    spec:
      containers:
      - name: cert-example
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: WHOAMI_PORT_NUMBER
          value: "8080"
