apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: whoami
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: docker.io/traefik/whoami:latest
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
