apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cert-example.fullname" . }}
  labels:
    {{- include "cert-example.labels" . | nindent 4 }}
spec:
  tls:
  - hosts:
{{- range .Values.dnsNames }}
      - {{ . }}
{{- end }}
    secretName: {{ include "cert-example.fullname" . }}
  rules:
{{- range .Values.dnsNames }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "cert-example.fullname" $ }}
            port:
              name: http
{{ end }}
