apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-example.fullname" . }}
  labels:
    {{- include "cert-example.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port | default 80 }}
    targetPort: http
  selector:
    {{- include "cert-example.selectorLabels" . | nindent 4 }}
